// src/recipesData.js
import './recipesdata.css';
export const RecipesData = [
    {
      id: 1,
      title: <h1>Quinoa Salad</h1>,
      image: 'https://www.allrecipes.com/thmb/AfZ5pJYvZSrlltkHiimLIOdEtjE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/229156-Zesty-Quinoa-Salad-ddmps-4x3-104421-df647e343ce543769a038cccf4c6419c.jpg',
      description: 'A nutritious salad made with quinoa and fresh vegetables.',
      calories: 350,
      type: 'vegetarian',
    },
    {
      id: 2,
      title: <h1>Grilled Chicken Breast</h1>,
      image: 'https://static01.nyt.com/images/2015/06/17/multimedia/clark-grilled-chicken/clark-grilled-chicken-superJumbo.jpg',
      description: 'Grilled chicken breast served with a side of steamed vegetables.',
      calories: 400,
      type: 'non-vegetarian',
    },
    {
      id: 3,
      title: <h1>Vegetable Stir-Fry</h1>,
      image: 'https://www.cookingclassy.com/wp-content/uploads/2023/01/vegetable-stir-fry-3.jpg',
      description: 'A mix of colorful vegetables stir-fried in a light sauce.',
      calories: 300,
      type: 'vegetarian',
    },
    {
      id: 4,
      title: <h1>Salmon with Lemon</h1>,
      image: 'https://www.cookingclassy.com/wp-content/uploads/2018/05/grilled-lemon-herb-salmon-7.jpg',
      description: 'Baked salmon with a lemon and dill sauce.',
      calories: 500,
      type: 'non-vegetarian',
    },
    {
      id: 5,
      title: <h1>Chickpea Curry</h1>,
      image: 'https://nishkitchen.com/wp-content/uploads/2020/01/Chicken-Chickpeas-Curry-1B.jpg',
      description: 'A spicy chickpea curry with a blend of aromatic spices.',
      calories: 400,
      type: 'vegetarian',
    },
    //  {
    //    id: 6,
    //   title: 'Turkey Lettuce Wraps',
    //   image: 'https://www.foodnetwork.com/content/dam/images/food/fullset/2012/1/19/1/MN0611H_turkey-lettuce-wraps_s4x3.jpg',
    //   description: 'Lean ground turkey served in lettuce wraps with fresh veggies.',
    //   calories: 350,
    //   type: 'non-vegetarian',
    // },
    {
      id: 7,
      title: <h1>Sweet Potato and Black Bean Chili</h1>,
      image: 'https://www.eatingwell.com/thmb/OhhPr2WJ8dLmV3mtf8A8JY8hc-8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/sweet-potato-black-bean-chili-250222-1x1-2a859b9966af411c9a145a406adcad8a.jpg',
      description: 'A hearty chili made with sweet potatoes and black beans.',
      calories: 450,
      type: 'vegetarian',
    },
    {
      id: 8,
      title: <h1>Grilled Shrimp Skewers</h1>,
      image: 'https://foolproofliving.com/wp-content/uploads/2021/08/Grilled-Shrimp-Kabobs-with-Vegetables-recipe-image.jpg',
      description: 'Delicious shrimp skewers grilled to perfection.',
      calories: 300,
      type: 'non-vegetarian',
    },
    {
      id: 9,
      title: <h1>Greek Yogurt and Berry Parfait</h1>,
      image: 'https://mediavine-res.cloudinary.com/image/upload/s--vrq9Vtrb--/ar_1:1,c_fill,f_auto,fl_lossy,q_auto/v1626061869/xcgyl4ktmsigomwav5ai.jpg',
      description: 'A healthy parfait made with Greek yogurt and fresh berries.',
      calories: 250,
      type: 'vegetarian',
    },
    // {
    //   id: 10,
    //   title: 'Chicken and Veggie Soup',
    //   image: 'https://www.marcellinaincucina.com/wp-content/uploads/2019/02/Chicken-and-Vegetable-Soup-blog-3.jpg',
    //   description: 'A light and comforting soup with chicken and assorted vegetables.',
    //   calories: 400,
    //   type: 'non-vegetarian',
    // },
  ];
  
  export default RecipesData;